### PR TITLE
Remove coder from kubernetes

### LINKED ISSUE #80: Deploy and configure the chosen cloud based IDE for all developers in the organization. Include documentation and training
Deploy and configure the chosen cloud based IDE for all developers in the organization, providing them with a personal and configurable work environment.

### PR DESCRIPTION
**Pull request by ThomasCardin**
- Closes #80 

Won't do. Removing coder from the cluster. See https://github.com/ai-cfia/howard/issues/77 for more information

### CODE REVIEW

**Comment by rngadam** [comment]
@ThomasCardin I'm seeing 5 commits but no files modified in this PR?

**Comment by ThomasCardin** [comment]
Yeah, I merged from main to continue my work on Coder since the deployment ins't working has expected

**Comment by ThomasCardin** [comment]
> Currently, an issue is open on the coder repository regarding a readiness and liveness probe problem. At the moment, we are unable to do anything with this deployment until we receive assistance. If it takes too long, we could contact them directly via their email...

@rngadam for why there is no commit right now

**Review by SonOfLope — APPROVED** [review]
byebye

**Pull request merged**
